<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    <PackageVersion Include="NCalc" Version="7.1.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
    <PackageVersion Include="MSTest" Version="4.0.2" />
  </ItemGroup>
</Project>
