import fs from 'node:fs';
import path from 'node:path';
import {starterSeed} from './northstar.mjs';
const out=path.resolve('artifacts/bcm-atlas');fs.mkdirSync(out,{recursive:true});
const op=(operationType,payload)=>({operationType,payload});const mutations=[];
const defs=[
 ['capability','Capability','cap',[
 ['name','Name','text',true],['code','Reference','text'],['description','Definition','text',false,'longText'],['parent','Parent capability','reference'],['owner','Accountable owner','text'],['maturity','Current maturity','integer',false,'rating',null,1,5],['target','Target maturity','integer',false,'rating',null,1,5],['importance','Strategic importance','text',false,'singleChoice',['Supporting','Core','Differentiating']],['investment','Investment direction','text',false,'singleChoice',['Tolerate','Invest','Migrate','Eliminate']],['lifecycle','Lifecycle','text',false,'singleChoice',['Proposed','Active','Retiring']],['reviewed','Last reviewed','date',false,'date'],['evidence','Assessment evidence','text',false,'longText'],['order','Display order','integer']]],
 ['application','Application','app',[
 ['name','Name','text',true],['code','Reference','text'],['description','Purpose','text',false,'longText'],['owner','Owner','text'],['lifecycle','Lifecycle','text',false,'singleChoice',['Planned','Active','Retiring']],['criticality','Criticality','text',false,'singleChoice',['Low','Medium','High']],['vendor','Vendor','text']]],
 ['support','Application support','support',[
 ['name','Support relationship','text',true],['capability','Capability','reference'],['application','Application','reference'],['role','Role','text',false,'singleChoice',['Primary','Supporting','System of record']],['fit','Business fit','text',false,'singleChoice',['Poor','Adequate','Strong']],['notes','Notes','text',false,'longText']]],
 ['initiative','Initiative','initiative',[
 ['name','Name','text',true],['code','Reference','text'],['capability','Primary capability','reference'],['description','Intended outcome','text',false,'longText'],['owner','Accountable owner','text'],['stage','Stage','text',false,'singleChoice',['Proposed','Discovery','Delivery','Complete']],['start','Start','date',false,'date'],['end','Target completion','date',false,'date'],['priority','Priority','text',false,'singleChoice',['Low','Medium','High']],['success','Success measure','text',false,'longText']]]
];
for(const [id,name,prefix,fields] of defs){mutations.push({description:`Define ${name}`,operations:[op('schema.createEntity',{entityId:`bcm.${id}`,displayName:name}),...fields.map(([key,label,kind,required=false,presentation,options,min,max])=>op('schema.addField',{entityId:`bcm.${id}`,fieldId:`${prefix}.${key}`,displayName:label,storageKind:kind,required,...(presentation?{presentation}:{}),...(options?{options}:{}),...(min?{min,max}:{})}))]});}
mutations.push({description:'Connect the model and its portfolio',operations:[...[
 ['capability','cap.parent','capability','cap.name'],['support','support.capability','capability','cap.name'],['support','support.application','application','app.name'],['initiative','initiative.capability','capability','cap.name']].map(([a,b,c,d])=>op('schema.configureReference',{entityId:`bcm.${a}`,fieldId:b,targetEntityId:`bcm.${c}`,labelFieldId:d})),
 // The capability tree is the Engine's to keep (ADR-0019): no loops, at most 32 levels, siblings by Display order.
 op('schema.declareHierarchy',{entityId:'bcm.capability',parentFieldId:'cap.parent',orderFieldId:'cap.order'}),op('application.setPurpose',{purpose:'Capability Atlas — a business capability model, maturity assessment and investment portfolio. The compact map uses the BCM reference layout v1.0.0 selected by the owner. Starter records describe Northstar, a fictional enterprise; all people, applications and initiatives are demonstration data. Replace them with your organisation. Maturity scale: 1 Initial, 2 Repeatable, 3 Defined, 4 Managed, 5 Optimising. Assessments are evidence-based judgments, not automatic measures. Parent links form a capability hierarchy; applications connect through support relationships and initiatives identify their primary capability.'})]});
const colors={Supporting:'grey',Core:'blue',Differentiating:'violet',Tolerate:'blue',Invest:'teal',Migrate:'amber',Eliminate:'red',Proposed:'grey',Active:'teal',Retiring:'amber',Planned:'violet',Low:'grey',Medium:'amber',High:'red',Poor:'red',Adequate:'amber',Strong:'teal',Discovery:'violet',Delivery:'blue',Complete:'green'};
const choices=[];for(const [id,,prefix,fields]of defs)for(const [key,,, ,presentation,options]of fields)if(presentation==='singleChoice')for(const choice of options)if(colors[choice])choices.push(op('schema.setChoiceMetadata',{entityId:`bcm.${id}`,fieldId:`${prefix}.${key}`,choiceId:choice,displayName:choice,retired:false,tone:colors[choice]}));for(let i=0;i<choices.length;i+=16)mutations.push({description:'Give assessment and portfolio choices semantic colours',operations:choices.slice(i,i+16)});
const nodes=[];let seq=0;const node=(id,kind,properties,parent=null,position=seq++)=>{nodes.push(op('ui.addNode',{surfaceId:'bcm.atlas',nodeId:`bcm.${id}`,kind,position,parentNodeId:parent?`bcm.${parent}`:null,properties}));return id;};const root=(id,kind,entity,title,extra={})=>node(id,kind,{definitionVersion:3,...(entity?{entityId:`bcm.${entity}`} :{}),title,...extra});const fields=(parent,prefix,keys)=>keys.forEach((k,i)=>node(`${parent}.${k}`,'fieldBinding',{fieldId:`${prefix}.${k}`},parent,i));
root('map','extensionRecordsSurface','capability','Capability map',{labelFieldId:'cap.name',statusFieldId:'cap.lifecycle',packageId:'org.nendo.bcm-atlas'});fields('map','cap',defs[0][3].map(x=>x[0]).filter(x=>x!=='name'));
root('outline','outlineSurface','capability','Capability outline',{titleFieldId:'cap.name',accentFieldId:'cap.lifecycle',expandDepth:2,reorder:true});fields('outline','cap',['code','owner','maturity','target']);
root('register','recordList','capability','Capability register',{orderByFieldId:'cap.code',orderDirection:'ascending'});fields('register','cap',['code','name','parent','owner','maturity','target','importance','investment']);
root('investment','boardSurface','capability','Investment directions',{groupByFieldId:'cap.investment',orderByFieldId:'cap.code'});fields('investment','cap',['name','code','owner','maturity','target']);
root('positioning','matrixSurface','capability','Strategic positioning',{rowByFieldId:'cap.importance',columnByFieldId:'cap.investment'});fields('positioning','cap',['name','code','maturity']);
root('apps','gallerySurface','application','Application landscape',{titleFieldId:'app.name',accentFieldId:'app.lifecycle'});fields('apps','app',['code','owner','criticality','vendor']);
root('supports','recordList','support','Application coverage');fields('supports','support',['name','capability','application','role','fit']);
root('portfolio','boardSurface','initiative','Change portfolio',{groupByFieldId:'initiative.stage'});fields('portfolio','initiative',['name','capability','owner','end','priority']);
root('roadmap','timelineSurface','initiative','Transformation roadmap',{dateFieldId:'initiative.start',endDateFieldId:'initiative.end',titleFieldId:'initiative.name',accentFieldId:'initiative.stage'});fields('roadmap','initiative',['capability','owner','success']);
for(const [id,,prefix,fs]of defs){const detail=`${id}.detail`;root(detail,'detailSurface',id,undefined,{titleFieldId:`${prefix}.name`,subtitleFieldId:`${prefix}.${id==='support'?'role':'code'}`,...(id==='capability'?{accentFieldId:'cap.investment'}:id==='application'?{accentFieldId:'app.lifecycle'}:id==='initiative'?{accentFieldId:'initiative.stage'}:{})});fields(detail,prefix,fs.map(x=>x[0]).filter(x=>x!=='order'&&x!=='name'));}
for(const [id,target,via,title,fs]of [['children','capability','cap.parent','Child capabilities',['code','name','maturity']],['coverage','support','support.capability','Application support',['name','application','fit']],['changes','initiative','initiative.capability','Related initiatives',['name','stage','end']]]){node(id,'relatedList',{targetEntityId:`bcm.${target}`,viaFieldId:via,title},'capability.detail');fields(id,target==='capability'?'cap':target,fs);}
node('appcoverage','relatedList',{targetEntityId:'bcm.support',viaFieldId:'support.application',title:'Capabilities supported'},'application.detail');fields('appcoverage','support',['name','capability','fit']);
root('home','overviewSurface',null,'Northstar · Capability Atlas',{description:'A fictional enterprise, ready to explore. Start with the Capability map to navigate the business; use investment directions and the change portfolio to turn assessment into action.'});
for(const [id,entity,title]of [['total','capability','Capabilities'],['applications','application','Applications'],['initiatives','initiative','Initiatives']])node(`home.${id}`,'summaryTile',{entityId:`bcm.${entity}`,aggregate:'count',title},'home');
node('home.directions','breakdownChart',{entityId:'bcm.capability',aggregate:'count',groupByFieldId:'cap.investment',title:'Investment direction'},'home');node('home.changes','breakdownChart',{entityId:'bcm.initiative',aggregate:'count',groupByFieldId:'initiative.stage',title:'Change portfolio'},'home');
// Keep schema and views in separately reviewable proposals, within host limits.
const batches=[];for(let i=0;i<nodes.length;i+=16)batches.push({description:'Compose capability modeling and portfolio screens',operations:nodes.slice(i,i+16)});
fs.writeFileSync(path.join(out,'schema.json'),JSON.stringify(mutations,null,2)+'\n');fs.writeFileSync(path.join(out,'surfaces.json'),JSON.stringify(batches,null,2)+'\n');
const seed=starterSeed();
fs.writeFileSync(path.join(out,'seed.json'),JSON.stringify(seed,null,2)+'\n');console.log(JSON.stringify({schemaOperations:mutations.flatMap(x=>x.operations).length,surfaceOperations:nodes.length,records:seed.length,byEntity:Object.fromEntries(defs.map(([id])=>[id,seed.filter(r=>r.entityId===`bcm.${id}`).length]))}));
