import {E,F,value,title,gap,hierarchy,projectHierarchy,validParent,maturityLabels,importanceOptions,investmentOptions,lifecycleOptions} from './model.js';
import {layoutCapabilities,fitViewport} from './layout-profile.js';
const $=id=>document.getElementById(id), el=(tag,cls,text)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(text!=null)x.textContent=text;return x;};
let records=[],applications=[],supports=[],initiatives=[],h=hierarchy([]),selected=null,scope=null,mode='map',colour='maturity',layoutMode='compact',levels=2,projection=null,query='',zoom=1,pan={x:20,y:20},layout=null,editing=null,loading=0,refreshTimer,dirty=false,modelGeneration=0,layoutKey=null;
const tones=['grey','red','orange','amber','teal','green'];
const toneFor=r=>{if(colour==='none')return 'grey';if(colour==='maturity')return tones[Number(value(r,'maturity'))]||'grey';if(colour==='gap'){const g=gap(r);return g==null?'grey':g<=0?'teal':g===1?'amber':g===2?'orange':'red';}if(colour==='importance')return {Supporting:'grey',Core:'blue',Differentiating:'violet'}[value(r,'importance')]||'grey';return {Tolerate:'blue',Invest:'teal',Migrate:'amber',Eliminate:'red'}[value(r,'investment')]||'grey';};
const tone=(node,t)=>node.style.setProperty('--tone',`var(--nendo-tone-${t})`);
const say=message=>$('status').textContent=message;
function button(label,fn,cls){const b=el('button',cls,label);b.type='button';b.addEventListener('click',async event=>{try{await fn(event);}catch(error){say(error.message);}});return b;}
function match(r){return !query||[title(r),value(r,'code'),value(r,'owner'),value(r,'description')].join(' ').toLowerCase().includes(query);}
function visibleRecords(){return scope&&h.byId.has(scope)?[h.byId.get(scope),...h.descendants(scope)]:records;}
function scopeTo(id){scope=id;selected=id;const depth=projectHierarchy(h,scope).maxDepth;if(Number.isFinite(levels))levels=Math.min(levels,Math.max(1,depth));render(true);}
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));render(true);}
function stats(){const visible=visibleRecords();$('total').textContent=visible.length;$('leaves').textContent=visible.filter(r=>!h.children.get(r.recordId)?.length).length;$('gaps').textContent=visible.filter(r=>gap(r)>0).length;$('unassessed').textContent=visible.filter(r=>value(r,'maturity')==null).length;}
function breadcrumbs(){const nav=$('breadcrumbs');nav.replaceChildren(button('Enterprise',()=>scopeTo(null)));const ancestors=[];let p=scope;while(p&&h.byId.has(p)){ancestors.unshift(p);p=h.parents.get(p);}for(const id of ancestors){nav.append(el('span','muted','/'),button(title(h.byId.get(id)),()=>scopeTo(id)));}}
function levelControls(){const control=$('levels');const active=document.activeElement?.dataset.level;control.replaceChildren();control.setAttribute('aria-label',scope?'Levels below the focused group':'Levels from the enterprise');for(const [v,label] of [...Array.from({length:Math.max(1,projection.maxDepth)},(_,i)=>[i+1,String(i+1)]),[Infinity,'All']]){const b=button(label,()=>{levels=v;render(true);});b.dataset.level=String(v);b.setAttribute('aria-label',v===Infinity?'Show all levels':`Show ${v} level${v===1?'':'s'}${scope?' below this group':''}`);b.setAttribute('aria-pressed',String(levels===v));control.append(b);}if(active)control.querySelector(`[data-level="${active}"]`)?.focus();}
function legend(){const labels=colour==='maturity'?maturityLabels.map((s,i)=>[s,tones[i]]):colour==='gap'?[['At / above target','teal'],['1 level','amber'],['2 levels','orange'],['3+ levels','red'],['Unassessed','grey']]:colour==='importance'?[['Supporting','grey'],['Core','blue'],['Differentiating','violet']]:colour==='investment'?[['Tolerate','blue'],['Invest','teal'],['Migrate','amber'],['Eliminate','red']]:[['Neutral','grey']];$('legend').replaceChildren(...labels.map(([s,t])=>{const n=el('span');const dot=el('i');tone(dot,t);n.append(dot,document.createTextNode(s));return n;}));}
function applyTransform(){$('drawing').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('zoom').textContent=`${Math.round(zoom*100)}%`;}
function fit(){if(!layout)return;const camera=fitViewport(layout,$('map').getBoundingClientRect());if(!camera)return;zoom=camera.zoom;pan=camera.pan;applyTransform();}
function zoomBy(factor){const box=$('map').getBoundingClientRect(),next=Math.max(.02,Math.min(Math.max(8,zoom),zoom*factor));pan={x:box.width/2-(box.width/2-pan.x)*next/zoom,y:box.height/2-(box.height/2-pan.y)*next/zoom};zoom=next;applyTransform();}
function renderMap(refit){if(!projection.tree.length){layout=null;$('drawing').replaceChildren();return;}
  // Search and colour only restyle cards; the packing depends on the tree alone, so reuse it.
  const key=[modelGeneration,scope,levels,layoutMode].join('|');
  if(key!==layoutKey){layout=layoutCapabilities(window.BcmLayout,projection.tree,layoutMode);layoutKey=null;const validation=window.BcmLayout.validateBcmLayout(layout);if(validation.length)throw new Error('Layout geometry validation failed: '+validation.map(x=>x.message).join('; '));layoutKey=key;}
  const drawing=$('drawing');drawing.replaceChildren();drawing.style.width=`${layout.width}px`;drawing.style.height=`${layout.height}px`;
  const matches=new Set(records.filter(match).map(r=>r.recordId));if(query)for(const id of [...matches]){let p=h.parents.get(id);while(p){matches.add(p);p=h.parents.get(p);}}
  for(const n of layout.nodes){if(n.synthetic)continue;const r=h.byId.get(n.id),isGroup=!!h.children.get(n.id)?.length,hidden=n.isLeaf&&isGroup?projection.hiddenCounts.get(n.id):0;const b=button('',()=>select(n.id),`cap ${n.isLeaf?'leaf':'branch'}${selected===n.id?' selected':''}${query&&!matches.has(n.id)?' dim':''}${query&&match(r)?' matched':''}`);b.dataset.id=n.id;b.setAttribute('aria-label',`${title(r)}, ${maturityLabels[value(r,'maturity')||0]}${isGroup?', group':''}${hidden?', '+hidden+' capabilities inside':''}`);b.setAttribute('aria-pressed',String(selected===n.id));b.title=`${value(r,'code')||''} ${title(r)}\n${isGroup?'Double-click to focus this group':'Select to inspect'}`;Object.assign(b.style,{left:`${n.x}px`,top:`${n.y}px`,width:`${n.width}px`,height:`${n.height}px`});tone(b,toneFor(r));b.append(el('span','cap-title',title(r)));if(n.isLeaf){b.append(el('span','cap-meta',String(value(r,'code')||'')),el('span',hidden?'score cap-count':'score',hidden?`${hidden} inside`:colour==='gap'?(gap(r)==null?'—':`Δ ${gap(r)}`):value(r,'maturity')==null?'—':`${value(r,'maturity')} / 5`));}b.addEventListener('dblclick',()=>{if(isGroup)scopeTo(n.id);});drawing.append(b);}
  if(refit)fit();else applyTransform();
}
function renderTable(){const rows=projection.rows;const filtered=rows.filter(({r})=>match(r));if(mode==='assessment')filtered.sort((a,b)=>(gap(b.r)??-99)-(gap(a.r)??-99)||title(a.r).localeCompare(title(b.r)));
  const table=el('table'),head=el('thead'),hr=el('tr');for(const text of ['Capability','Maturity','Target','Gap','Importance','Direction'])hr.append(el('th',null,text));head.append(hr);table.append(head);const body=el('tbody');for(const {r,depth} of filtered){const tr=el('tr',selected===r.recordId?'selected':'');tr.dataset.id=r.recordId;const name=el('td','name');const b=button(title(r),()=>select(r.recordId));b.style.border='0';b.style.background='transparent';b.style.textAlign='left';if(mode==='outline')b.style.marginLeft=`${depth*18}px`;name.append(b,el('div','eyebrow',String(value(r,'code')||'')));tr.append(name);for(const [k,text] of [['maturity',value(r,'maturity')==null?'—':`${value(r,'maturity')} · ${maturityLabels[value(r,'maturity')]}`],['target',value(r,'target')??'—'],['gap',gap(r)==null?'—':gap(r)>0?`+${gap(r)}`:String(gap(r))],['importance',value(r,'importance')||'—'],['investment',value(r,'investment')||'—']])tr.append(el('td',k==='gap'&&gap(r)>0?'gap numeric':'numeric',String(text)));tr.addEventListener('click',()=>select(r.recordId));body.append(tr);}table.append(body);$('table').replaceChildren(table);if(!filtered.length)$('table').append(el('p','muted','No capabilities match your search.'));
}
function select(id){selected=id;document.querySelectorAll('[data-id]').forEach(b=>{b.classList.toggle('selected',b.dataset.id===id);if(b.classList.contains('cap'))b.setAttribute('aria-pressed',String(b.dataset.id===id));});inspector();}
function inspector(){const panel=$('inspector');panel.replaceChildren();const r=h.byId.get(selected);if(!r){panel.append(el('div','eyebrow','BUSINESS CAPABILITY MODEL'),el('h2',null,'The enterprise, at a glance.'),el('p',null,'Explore what the organisation does, how well it does it, and where to invest next.'));panel.append(el('h3',null,'Read the map'),el('p',null,'Select a capability to inspect it. Double-click a group to focus. Colour reveals maturity, strategic importance or investment direction.'),el('h3',null,'A model you can evolve'),el('p',null,'Create capabilities, organise the hierarchy and record assessments. Link applications and initiatives through the record page.'),button('+ Top-level capability',()=>edit(null,null),'primary'));return;}
  panel.append(el('div','eyebrow',String(value(r,'code')||'CAPABILITY')),el('h2',null,title(r)));const badges=el('div');for(const k of ['lifecycle','importance','investment'])if(value(r,k))badges.append(el('span','badge',value(r,k)));panel.append(badges,el('p',null,value(r,'description')||'No definition yet. Describe the business outcome this capability enables.'));
  panel.append(el('h3',null,'Assessment'));const facts=el('div','facts');for(const [label,txt] of [['Current',value(r,'maturity')==null?'Unassessed':`${value(r,'maturity')} · ${maturityLabels[value(r,'maturity')]}`],['Target',value(r,'target')==null?'Unassessed':`${value(r,'target')} · ${maturityLabels[value(r,'target')]}`],['Owner',value(r,'owner')||'Unassigned'],['Reviewed',value(r,'reviewed')||'Not yet']]){const d=el('div');d.append(el('span',null,label),el('strong',null,txt));facts.append(d);}panel.append(facts);const scale=el('div','scale');tone(scale,toneFor(r));for(let i=1;i<=5;i++)scale.append(el('i',i<=Number(value(r,'maturity'))?'filled':''));panel.append(scale);if(gap(r)>0)panel.append(el('p','gap',`${gap(r)} maturity level${gap(r)===1?'':'s'} below target.`));if(value(r,'evidence'))panel.append(el('p',null,value(r,'evidence')));
  const actions=el('div','inspector-actions');actions.append(button('Edit',()=>edit(r)),button('+ Child',()=>edit(null,r.recordId)),button('Open record',()=>nendo.ui.openRecord(E,r.recordId)));if(h.children.get(r.recordId)?.length)actions.append(button('Focus group',()=>scopeTo(r.recordId)));panel.append(actions);
  const child=h.children.get(r.recordId)||[];if(child.length){panel.append(el('h3',null,`${child.length} child capabilities`));for(const c of child)panel.append(button(title(c),()=>select(c.recordId),'relation'));}
  const links=supports.filter(x=>x.values['support.capability']===r.recordId);panel.append(el('h3',null,'Application support'));if(!links.length)panel.append(el('p',null,'No applications linked. Add support links in the record page.'));for(const link of links){const app=applications.find(a=>a.recordId===link.values['support.application']);const b=button(app?.values['app.name']||'Missing application',()=>nendo.ui.openRecord('bcm.support',link.recordId),'relation');b.append(el('small',null,`${link.values['support.fit']||'Unassessed'} fit · ${link.values['support.role']||'Support'}`));panel.append(b);}
  const projects=initiatives.filter(x=>x.values['initiative.capability']===r.recordId);panel.append(el('h3',null,'Change portfolio'));if(!projects.length)panel.append(el('p',null,'No initiatives linked.'));for(const p of projects){const b=button(p.values['initiative.name'],()=>nendo.ui.openRecord('bcm.initiative',p.recordId),'relation');b.append(el('small',null,`${p.values['initiative.stage']||'Proposed'} · ${p.values['initiative.end']||'No target date'}`));panel.append(b);}
}
function render(refit=false){projection=projectHierarchy(h,scope,levels);levelControls();stats();breadcrumbs();legend();$('empty').hidden=records.length!==0;$('map').hidden=mode!=='map'||!records.length;$('table').hidden=mode==='map'||!records.length;document.querySelector('.map-tools').hidden=mode!=='map';if(mode==='map')renderMap(refit);else renderTable();inspector();const count=visibleRecords().filter(match).length;const shown=projection.rows.filter(({r})=>match(r)).length;say(query?`${count} matches · ${shown} shown${count>shown?' · Choose All levels to reveal deeper matches':''}`:`${projection.rows.length} shown · ${visibleRecords().length} in scope · ${records.length} total`);$('notice').hidden=!h.issues.length;$('notice').textContent=h.issues.join(' ');}
async function refresh(){const generation=++loading;try{const loaded=await Promise.all([nendo.view.loadRecords(),nendo.records.queryAll({entityId:'bcm.application'},{max:5000}),nendo.records.queryAll({entityId:'bcm.support'},{max:5000}),nendo.records.queryAll({entityId:'bcm.initiative'},{max:5000})]);if(generation!==loading)return;const first=layout===null;[records,applications,supports,initiatives]=loaded;modelGeneration++;h=hierarchy(records);if(!h.byId.has(selected))selected=null;const lostScope=scope!==null&&!h.byId.has(scope);if(lostScope)scope=null;render(first||lostScope);}catch(error){say(`Could not load model: ${error.message}`);$('notice').hidden=false;$('notice').textContent='The model could not be refreshed. Your current view is retained. '+error.message;}}
function fillSelect(name,options,current,empty='Not assessed'){const s=$('edit-form').elements[name];s.replaceChildren();if(empty!==null)s.append(new Option(empty,''));for(const option of options){const [v,label]=Array.isArray(option)?option:[option,option];s.append(new Option(label,String(v)));}s.value=current==null?'':String(current);}
function edit(record,parent){editing=record;dirty=false;const form=$('edit-form');form.reset();$('form-error').textContent='';$('edit-title').textContent=record?'Edit capability':'New capability';for(const key of ['name','code','owner','description','evidence','reviewed'])form.elements[key].value=value(record,key)||'';fillSelect('maturity',maturityLabels.slice(1).map((l,i)=>[i+1,`${i+1} · ${l}`]),value(record,'maturity'));fillSelect('target',maturityLabels.slice(1).map((l,i)=>[i+1,`${i+1} · ${l}`]),value(record,'target'));fillSelect('importance',importanceOptions,value(record,'importance'));fillSelect('investment',investmentOptions,value(record,'investment'));fillSelect('lifecycle',lifecycleOptions,value(record,'lifecycle')||'Proposed',null);fillSelect('parent',records.filter(r=>validParent(records,record?.recordId,r.recordId)).sort((a,b)=>title(a).localeCompare(title(b))).map(r=>[r.recordId,`${value(r,'code')||''} ${title(r)}`]),record?value(record,'parent'):parent,'Enterprise / top level');$('editor').showModal();form.elements.name.focus();}
function closeEditor(){if(dirty&&!confirm('Discard your unsaved changes?'))return;$('editor').close();}
$('edit-form').addEventListener('input',()=>dirty=true);$('editor').addEventListener('cancel',e=>{e.preventDefault();closeEditor();});$('close-editor').onclick=closeEditor;$('cancel-editor').onclick=closeEditor;
$('edit-form').onsubmit=async event=>{event.preventDefault();const form=event.target,values={};for(const key of ['name','code','owner','description','evidence','reviewed','parent','importance','investment','lifecycle'])values[F[key]]=form.elements[key].value.trim()||null;for(const key of ['maturity','target'])values[F[key]]=form.elements[key].value?Number(form.elements[key].value):null;if(!values[F.name])return;if(!validParent(records,editing?.recordId,values[F.parent])){$('form-error').textContent='Choose a parent outside this capability’s descendants.';return;}$('save').disabled=true;try{const target=values[F.parent]?await nendo.records.get(E,values[F.parent]):null;const options=target?{targetVersions:{[F.parent]:target.version}}:{};const saved=editing?await nendo.records.update(editing,values,options):await nendo.records.create(E,values,options);selected=saved.recordId;dirty=false;$('editor').close();await refresh();say('Capability saved.');}catch(error){$('form-error').textContent=`Your changes have not been saved. ${error.message} Your draft is still here.`;}finally{$('save').disabled=false;}};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('search').oninput=e=>{query=e.target.value.toLowerCase().trim();render(false);};$('colour').onchange=e=>{colour=e.target.value;render(false);};$('layout').onchange=e=>{layoutMode=e.target.value;render(true);};$('add').onclick=()=>edit(null,scope);$('empty-add').onclick=()=>edit(null,null);$('fit').onclick=fit;$('zoom-in').onclick=()=>zoomBy(1.2);$('zoom-out').onclick=()=>zoomBy(1/1.2);
let drag=null,suppressPanClick=false,panMode=false;
const map=$('map');
function endPan(cancelled=false){if(drag)suppressPanClick=!cancelled&&drag.moved;drag=null;map.classList.remove('panning');}
function activatePan(e){if(!drag||drag.active)return;drag.active=true;map.setPointerCapture(e.pointerId);}
function movePan(e){
  if(!drag||drag.pointerId!==e.pointerId)return;
  if(!drag.active&&(panMode||e.ctrlKey||e.metaKey))activatePan(e);
  if(!drag.active)return;
  const dx=e.clientX-drag.x,dy=e.clientY-drag.y;
  if(!drag.moved&&Math.hypot(dx,dy)<4)return;
  drag.moved=true;map.classList.add('panning');
  pan={x:drag.px+dx,y:drag.py+dy};applyTransform();
}
$('pan-tool').onclick=()=>{panMode=!panMode;endPan(true);map.classList.toggle('pan-ready',panMode);$('pan-tool').setAttribute('aria-pressed',String(panMode));};
map.addEventListener('pointerdown',e=>{
  suppressPanClick=false;
  if(e.button!==0)return;
  drag={pointerId:e.pointerId,x:e.clientX,y:e.clientY,px:pan.x,py:pan.y,moved:false,active:false};
  if(panMode||e.ctrlKey||e.metaKey||!e.target.closest('button')){activatePan(e);e.preventDefault();}
});
map.addEventListener('pointermove',e=>{if(drag&&!(e.buttons&1)){endPan(true);return;}movePan(e);});
map.addEventListener('pointerup',e=>{if(drag?.pointerId===e.pointerId){if(drag.active)movePan(e);endPan();}});
map.addEventListener('pointercancel',()=>endPan(true));
map.addEventListener('lostpointercapture',()=>{if(drag)endPan(true);});
window.addEventListener('blur',()=>endPan(true));
map.addEventListener('dragstart',e=>e.preventDefault());
map.addEventListener('click',e=>{if(suppressPanClick||panMode){suppressPanClick=false;e.preventDefault();e.stopImmediatePropagation();}},true);
map.addEventListener('dblclick',e=>{if(panMode||e.ctrlKey||e.metaKey){e.preventDefault();e.stopImmediatePropagation();}},true);
$('map').addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();zoomBy(e.deltaY<0?1.1:1/1.1);}}, {passive:false});$('map').addEventListener('keydown',e=>{if(e.target!==$('map'))return;if(e.key==='+'||e.key==='=')zoomBy(1.2);else if(e.key==='-')zoomBy(1/1.2);else if(e.key==='0')fit();else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){pan.x+=e.key==='ArrowLeft'?30:e.key==='ArrowRight'?-30:0;pan.y+=e.key==='ArrowUp'?30:e.key==='ArrowDown'?-30:0;applyTransform();}else return;e.preventDefault();});
let resizeTimer;new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(mode==='map'&&records.length)fit();},120);}).observe($('workspace'));
try{const context=await nendo.ready;if(context.configuration?.mode)setMode(context.configuration.mode);await refresh();nendo.on('changes',()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,150);});nendo.on('context',refresh);}catch(error){say(`Cannot start Capability Atlas: ${error.message}`);}
