using System.ComponentModel;
using System.Reflection;
using ModelContextProtocol.Server;

namespace Nendo.LocalMcp;

/// <summary>One read path this host serves, with what it answers.</summary>
public sealed record NendoMcpRead(string Name, string Uri, bool Templated, string Purpose);

/// <summary>
/// Every resource URI this host serves, generated by reflecting over the declared
/// resources so the index cannot drift from what is registered.
/// <para>
/// This exists because <c>resources/list</c> returns only the resources whose URI
/// has no parameter. The templated ones — records, entity schema, revision
/// operations, history — are returned by <c>resources/templates/list</c>, which a
/// client is not obliged to call and several do not. An agent that listed
/// resources therefore saw seven entries, concluded there was no way to read a
/// record back, and treated the data API as write-only. The read paths are now
/// named in the one read the server instructions send a client to first.
/// </para>
/// </summary>
internal static class NendoMcpReadIndex
{
    internal static IReadOnlyList<NendoMcpRead> All { get; } = typeof(NendoMcpResources)
        .GetMethods(BindingFlags.Public | BindingFlags.Instance)
        .Select(method => (
            Resource: method.GetCustomAttribute<McpServerResourceAttribute>(),
            Purpose: method.GetCustomAttribute<DescriptionAttribute>()?.Description ?? string.Empty))
        .Where(item => item.Resource?.Name is not null && item.Resource.UriTemplate is not null)
        .Select(item => new NendoMcpRead(
            item.Resource!.Name!,
            item.Resource.UriTemplate!,
            item.Resource.UriTemplate!.Contains('{', StringComparison.Ordinal),
            Sentence(item.Purpose)))
        .OrderBy(read => read.Name, StringComparer.Ordinal)
        .ToArray();

    /// <summary>The first sentence of a resource description: the index names paths, not their full contracts.</summary>
    private static string Sentence(string description)
    {
        var stop = description.IndexOf(". ", StringComparison.Ordinal);
        return stop < 0 ? description : description[..(stop + 1)];
    }
}
