import fs from 'node:fs';import assert from 'node:assert/strict';
import {frame,evaluate,command,main,waitFor,screenshot,bridge,close} from './cdp.mjs';
const report={checks:[],measurements:{}};let f,recordCount,domainCount;const created=[];const check=(ok,text)=>{assert.ok(ok,text);report.checks.push(text);console.log('PASS '+text);};const run=code=>evaluate(f,code);const click=selector=>run(`document.querySelector(${JSON.stringify(selector)}).click()`);const choose=(selector,value)=>run(`{const x=document.querySelector(${JSON.stringify(selector)});x.value=${JSON.stringify(value)};x.dispatchEvent(new Event('change',{bubbles:true}));}`);const fill=(selector,value)=>run(`{const x=document.querySelector(${JSON.stringify(selector)});x.value=${JSON.stringify(value)};x.dispatchEvent(new Event('input',{bubbles:true}));}`);
const ready=()=>waitFor(()=>run(`document.querySelectorAll('.cap').length===${recordCount}`),'all map cards');
try{
const snapshot=await bridge('session.getSnapshot');assert.equal(snapshot.fileName,'BCM.nendo','This journey is only for the BCM application.');
f=await frame();await run(`document.querySelector('#breadcrumbs button')?.click();document.querySelector('[data-level="Infinity"]')?.click()`);recordCount=await run('nendo.view.loadRecords().then(rows=>rows.length)');domainCount=await run(`(async()=>{const rows=await nendo.view.loadRecords();const visit=id=>1+rows.filter(r=>r.values['cap.parent']===id).reduce((n,r)=>n+visit(r.recordId),0);return visit('bcm-cap-6');})()`);assert.equal(await run(`nendo.records.queryAll({entityId:'bcm.capability'}).then(rows=>rows.filter(r=>r.values['cap.code']==='TEST-BCM').length)`),0,'A previous test record needs review before this journey runs.');await ready();await command('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false},main);await new Promise(r=>setTimeout(r,400));
check(await run(`document.querySelectorAll('.cap').length===${recordCount}`),'All capabilities render in the real Nendo frame');
const geometry=await run(`(()=>{const heads=[...document.querySelectorAll('.cap.branch')].map(x=>{const a=x.getBoundingClientRect(),b=x.querySelector('.cap-title').getBoundingClientRect();return {id:x.dataset.id,offset:b.top-a.top,titleHeight:b.height,width:b.width};});return {heads,tiles:document.querySelectorAll('.cap').length,viewport:[innerWidth,innerHeight],overflow:document.documentElement.scrollWidth>innerWidth};})()`);report.measurements.geometry=geometry;check(geometry.heads.every(x=>x.offset>=0&&x.offset<3&&x.titleHeight>0),'Every group heading is anchored in its reserved top header');check(!geometry.overflow,'Desktop frame has no horizontal document overflow');
await run(`document.head.insertAdjacentHTML('beforeend','<style id="defect-probe">.cap.branch .cap-title{top:50%!important}</style>')`);const detects=await run(`[...document.querySelectorAll('.cap.branch')].some(x=>x.querySelector('.cap-title').getBoundingClientRect().top-x.getBoundingClientRect().top>3)`);await run(`document.querySelector('#defect-probe').remove()`);check(detects,'Heading guard rejects the reintroduced displaced-header defect');
await screenshot('bcm-map-light');
await fill('#search','data governance');check(await run(`document.querySelectorAll('.cap.matched').length===1&&document.querySelector('.cap.matched').textContent.includes('Data governance')`),'Search finds the correct capability without dropping its context');await fill('#search','');
await click('.cap[data-id="bcm-cap-6-3-1"]');check(await run(`document.querySelector('#inspector').innerText.includes('Atlas Data')&&document.querySelector('#inspector').innerText.includes('Trusted data foundations')`),'Capability inspector traces both application support and investment initiative');
await choose('#colour','gap');check(await run(`document.querySelector('#legend').innerText.includes('3+ levels')`),'Maturity gap overlay and legend switch together');
await click('[data-mode="assessment"]');check(await run(`document.querySelectorAll('#table tbody tr').length===${recordCount}`),'Assessment table contains all capabilities');await screenshot('bcm-assessment-light');
await click('[data-mode="outline"]');check(await run(`document.querySelectorAll('#table tbody tr').length===${recordCount}`),'Outline preserves every capability');await click('[data-mode="map"]');
await run(`document.querySelector('.cap[data-id="bcm-cap-6"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))`);check(await run(`document.querySelectorAll('.cap').length===${domainCount}&&document.querySelector('#breadcrumbs').innerText.includes('Enterprise enablement')`),'Drill-down scopes to the selected domain and exposes a breadcrumb');await click('#breadcrumbs button');await ready();
await click('#add');await fill('[name="name"]','BCM journey verification');await fill('[name="code"]','TEST-BCM');await choose('[name="maturity"]','2');await choose('[name="target"]','4');await click('#save');await waitFor(()=>run(`!document.querySelector('#editor').open`),'create capability');const testRecord=await run(`nendo.records.queryAll({entityId:'bcm.capability'}).then(rows=>rows.find(r=>r.values['cap.code']==='TEST-BCM'))`);created.push(testRecord.recordId);check(testRecord.values['cap.maturity']===2&&testRecord.values['cap.target']===4,'Form creates and persists a real capability with assessment');
await run(`document.querySelector('.cap[data-id="${testRecord.recordId}"]').click();[...document.querySelectorAll('#inspector button')].find(b=>b.textContent==='Edit').click();`);await choose('[name="parent"]','bcm-cap-6');await fill('[name="name"]','BCM journey verification — edited');await click('#save');await waitFor(()=>run(`!document.querySelector('#editor').open`),'edit capability');const edited=await run(`nendo.records.get('bcm.capability',${JSON.stringify(testRecord.recordId)})`);check(edited.values['cap.parent']==='bcm-cap-6'&&edited.values['cap.name'].endsWith('edited'),'Editing persists both name and hierarchy reference with target versions');
await run(`document.querySelector('.cap[data-id="bcm-cap-6"]').click();[...document.querySelectorAll('#inspector button')].find(b=>b.textContent==='Edit').click();`);check(await run(`![...document.querySelector('[name="parent"]').options].some(o=>o.value===${JSON.stringify(testRecord.recordId)})`),'Parent picker excludes descendants to prevent a cycle');await click('#cancel-editor');
await run(`document.querySelector('.cap[data-id="${testRecord.recordId}"]').click();[...document.querySelectorAll('#inspector button')].find(b=>b.textContent==='Edit').click();`);await fill('[name="name"]','Unsaved draft survives conflict');await run(`(async()=>{const r=await nendo.records.get('bcm.capability',${JSON.stringify(testRecord.recordId)});await nendo.records.update(r,{'cap.owner':'Concurrent edit probe'});})()`);await click('#save');await waitFor(()=>run(`document.querySelector('#form-error').textContent.includes('not been saved')`),'stale version rejection');check(await run(`document.querySelector('#editor').open&&document.querySelector('[name="name"]').value==='Unsaved draft survives conflict'`),'Concurrent edit is refused and unsaved draft remains intact');report.measurements.conflict=await run(`document.querySelector('#form-error').textContent`);await run(`document.querySelector('#editor').close()`);
await run(`(async()=>{const r=await nendo.records.get('bcm.capability',${JSON.stringify(testRecord.recordId)});await nendo.records.delete(r);})()`);created.length=0;await ready();
await evaluate(main,`document.querySelector('[data-theme-option="dark"]').click()`);await waitFor(()=>run(`document.documentElement.dataset.nendoTheme==='dark'`),'dark theme');check(await run(`getComputedStyle(document.body).color!==getComputedStyle(document.body).backgroundColor`),'Dark theme reaches the embedded view with distinct ink and canvas');await screenshot('bcm-map-dark');
await command('Emulation.setDeviceMetricsOverride',{width:900,height:800,deviceScaleFactor:1,mobile:false},main);await new Promise(r=>setTimeout(r,400));check(await run(`document.documentElement.scrollWidth<=innerWidth`),'900px host width has no horizontal document overflow');await screenshot('bcm-narrow-dark');
await command('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false},main);await evaluate(main,`document.querySelector('[data-theme-option="light"]').click()`);await waitFor(()=>run(`document.documentElement.dataset.nendoTheme==='light'`),'restore light');await new Promise(r=>setTimeout(r,400));await choose('#colour','maturity');await click('#fit');await click('.cap[data-id="bcm-cap-6-3-1"]');await screenshot('bcm-final');
}catch(e){report.failure=e.stack;console.error(e.stack);process.exitCode=1;}finally{if(f)for(const id of created)try{await run(`(async()=>{const r=await nendo.records.get('bcm.capability',${JSON.stringify(id)});if(r)await nendo.records.delete(r);})()`);}catch(e){report.cleanupFailure=e.message;}fs.writeFileSync('artifacts/bcm-atlas/journey-results.json',JSON.stringify(report,null,2)+'\n');close();}
