import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {frame,evaluate,main,command,waitFor,screenshot,close} from './cdp.mjs';
import {hierarchy} from '../../../extensions/bcm-atlas/model.js';
import {selectionProbe} from './selection-probe.mjs';
const proof=JSON.parse(fs.readFileSync(new URL('../lab-reference-proof.json',import.meta.url),'utf8'));
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(new URL('../../../extensions/bcm-atlas/layout.js',import.meta.url),'utf8'),ctx);
const checks=[];const check=(ok,line)=>{assert.ok(ok,line);checks.push(line);console.log('PASS '+line);};let originalTheme;
try{await evaluate(main,`document.querySelector('[data-select-surface="bcm.map"]').click()`);const f=await frame();originalTheme=await evaluate(main,`document.querySelector('[data-theme-option][aria-pressed="true"]')?.dataset.themeOption`);await evaluate(f,`document.querySelector('#breadcrumbs button')?.click();document.querySelector('[data-level="Infinity"]')?.click()`);const recordCount=await evaluate(f,`nendo.view.loadRecords().then(r=>r.length)`);await waitFor(()=>evaluate(f,`document.querySelectorAll('.cap').length===${recordCount}`),'all capabilities');
const sourceRecords=await evaluate(f,'nendo.view.loadRecords()');const h=hierarchy(sourceRecords);const expected=ctx.window.BcmLayout.layoutBcm(h.roots.map(h.tree),proof.options).nodes.filter(n=>!n.synthetic).map(n=>[n.id,n.x,n.y,n.width,n.height]);
const bulkyEdges=()=>evaluate(f,`[...document.querySelectorAll('.cap')].filter(n=>parseFloat(getComputedStyle(n).borderLeftWidth)>1||[...n.querySelectorAll('.stripe')].some(s=>parseFloat(getComputedStyle(s).width)>1)).map(n=>n.dataset.id)`);
check((await bulkyEdges()).length===0,'Capability boxes have only a 1px outline and no bulky left stripe');
await evaluate(f,`{const s=document.createElement('i');s.id='stripe-regression-probe';s.className='stripe';s.style.cssText='position:absolute;left:0;top:0;bottom:0;width:4px';document.querySelector('.cap').append(s);}`);
const stripeDetected=(await bulkyEdges()).length>0;await evaluate(f,`document.querySelector('#stripe-regression-probe').remove()`);check(stripeDetected,'Stripe guard rejects the reintroduced 4px left-edge defect');
const rendered=()=>evaluate(f,`[...document.querySelectorAll('.cap')].map(n=>[n.dataset.id,parseFloat(n.style.left),parseFloat(n.style.top),parseFloat(n.style.width),parseFloat(n.style.height)])`);
assert.equal(JSON.stringify(await rendered()),JSON.stringify(expected),'Rendered map coordinates differ from the lab reference');check(true,`All ${recordCount} rendered capability rectangles equal the lab reference coordinates`);
for(const c of proof.cases){const geometry=await evaluate(f,`import('./layout-profile.js').then(p=>p.layoutCapabilities(window.BcmLayout,${JSON.stringify(c.tree)},${JSON.stringify(c.mode)}).nodes.map(n=>[n.id,n.parentId,n.x,n.y,n.width,n.height]))`);check(crypto.createHash('sha256').update(JSON.stringify(geometry)).digest('hex')===c.geometrySha256,'Installed package matches frozen lab coordinates: '+c.name);}
for(const width of [2560,1600,900]){await command('Emulation.setDeviceMetricsOverride',{width,height:width===2560?1440:1000,deviceScaleFactor:1,mobile:false},main);await new Promise(r=>setTimeout(r,300));assert.equal(JSON.stringify(await rendered()),JSON.stringify(expected),'Resize changed the packing');check(true,`Window width ${width}: only display scale changes; packing is identical`);
const fitted=await evaluate(f,`(()=>{document.querySelector('#fit').click();const box=document.querySelector('#map').getBoundingClientRect();const rects=[...document.querySelectorAll('.cap')].map(n=>n.getBoundingClientRect());const b={left:Math.min(...rects.map(r=>r.left)),right:Math.max(...rects.map(r=>r.right)),top:Math.min(...rects.map(r=>r.top)),bottom:Math.max(...rects.map(r=>r.bottom))};return {fill:Math.max((b.right-b.left)/(box.width-24),(b.bottom-b.top)/(box.height-24)),contained:b.left>=box.left+11.5&&b.right<=box.right-11.5&&b.top>=box.top+11.5&&b.bottom<=box.bottom-11.5,chrome:box.top};})()`);
assert.ok(fitted.fill>=.995&&fitted.fill<=1.005&&fitted.contained,`Fit underfills or clips the visible map at width ${width}: ${(fitted.fill*100).toFixed(1)}% of limiting dimension`);check(true,`Fit uses ${(fitted.fill*100).toFixed(1)}% of the limiting dimension at width ${width}, with all cards inside the canvas`);
if(width===2560){const capped=await evaluate(f,`(()=>{const d=document.querySelector('#drawing'),box=document.querySelector('#map').getBoundingClientRect(),w=parseFloat(d.style.width),h=parseFloat(d.style.height),z=Math.min(1.3,(box.width-36)/w,(box.height-36)/h);d.style.transform='translate('+((box.width-w*z)/2)+'px,'+((box.height-h*z)/2)+'px) scale('+z+')';const rs=[...document.querySelectorAll('.cap')].map(n=>n.getBoundingClientRect());const usedW=Math.max(...rs.map(r=>r.right))-Math.min(...rs.map(r=>r.left)),usedH=Math.max(...rs.map(r=>r.bottom))-Math.min(...rs.map(r=>r.top));const fill=Math.max(usedW/(box.width-24),usedH/(box.height-24));document.querySelector('#fit').click();return fill;})()`);check(capped<.995,`Canvas-fill guard rejects the reintroduced 130% cap (${(capped*100).toFixed(1)}% fill)`);}
if(width>=1600)check(fitted.chrome<150,`Map controls occupy ${fitted.chrome.toFixed(1)}px rather than more than 150px`);
}
await command('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false},main);await new Promise(r=>setTimeout(r,300));
const collision=await evaluate(f,`[...document.querySelectorAll('.cap.leaf')].filter(n=>n.querySelector('.cap-title').getBoundingClientRect().bottom>n.querySelector('.cap-meta').getBoundingClientRect().top+.1).map(n=>n.dataset.id)`);check(collision.length===0,'Leaf labels do not overlap their references at the restored 160 × 56 geometry');
for(const theme of ['dark','light']){await evaluate(main,`document.querySelector('[data-theme-option="${theme}"]').click()`);await waitFor(()=>evaluate(f,`document.documentElement.dataset.nendoTheme==='${theme}'`),theme);await new Promise(r=>setTimeout(r,150));const selection=await evaluate(f,selectionProbe);check(selection.hidden.length===0,selection.hidden[0]||theme+': '+selection.groups+' parent selections preserve children at '+selection.points+' points and allow '+selection.clicks+' child selections');await screenshot('bcm-lab-parity-'+theme);}
await evaluate(f,`{const s=document.createElement('style');s.id='selection-regression-probe';s.textContent='.cap.selected{z-index:2}';document.head.append(s);}`);
let regression;try{regression=await evaluate(f,selectionProbe);}finally{await evaluate(f,`document.querySelector('#selection-regression-probe').remove()`);}
check(regression.hidden.length>0,'Selection guard rejects the reintroduced stacking defect: '+regression.hidden[0]);
fs.writeFileSync('artifacts/bcm-atlas/layout-parity-results.json',JSON.stringify({checks,rectangles:expected.length},null,2)+'\n');
}finally{if(originalTheme)await evaluate(main,`document.querySelector('[data-theme-option="${originalTheme}"]').click()`);await command('Emulation.clearDeviceMetricsOverride',{},main);close();}
